version: '3.1'
services:
    mariadb:
      image: mariadb:latest
      container_name: java-ee-final-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=java-ee-final
        - MYSQL_USER=java-ee-final
        - MYSQL_PASSWORD=java-ee-final
      ports:
        - "8159:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: java-ee-final-phpmyadmin
      links:
        - mariadb:db
      ports:
        - "8259:80"
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
